### PR TITLE
Expose Mocha --timeout flag to etherlime test

### PR DESCRIPTION
**Pull request by BenSchZA**
By default the Mocha test-suite timeout is currently 2000 ms. By exposing the timeout flag through the CLI we can set this on the fly. 2000ms has already been established to be too short, as shown in this issue: https://github.com/LimeChain/etherlime/issues/122 ~ the solution of adding `this.timeout(...)` doesn't work well for arrow functions.

This PR makes the following changes:
1. Add timeout flag to `etherlime test` CLI
2. Set default Mocha timeout to 10s

Unit tests are in the process of being written.

### CODE REVIEW

**Comment by BenSchZA** [comment]
> Please pull the last changes from `master` branch and update your pull request.
> Thank you.

Thanks for the review! Completed change.

**Comment by BenSchZA** [comment]
@ochikov Apologies for the delay. I've merged latest master into PR branch.

**Comment by BenSchZA** [comment]
Hey @ochikov . Just want to check what the status is here? We're using this branch in some of our code because of the timeout issue, and merging master into this branch seems to have broken some functionality. Can we continue with this PR and get it merged?

**Comment by ochikov** [comment]
This option will be available in the next release as well as unit tests for it.

**Pull request closed without merging**
